
CREATE TABLE DWH_COVER_FACT
(
  RECORD_VALID_FROM DATE NOT NULL
, RECORD_VALID_UNTIL DATE
, AMT_TYPE VARCHAR2(4 CHAR) NOT NULL
, COVER_AMT NUMBER(22, 2)
, COVER_PERC NUMBER(5, 2)
, COVER_CCY_KEY NUMBER(12, 0)
, SYSTEM_ID VARCHAR2(3 CHAR)
, COVER_KEY VARCHAR2(38 CHAR)
, LOAD_KEY NUMBER(24, 0)
, BATCH_ID NUMBER(24, 0)
, COVER_VALUE_DATE DATE
, COVER_VALUE_TYPE_KEY NUMBER(12, 0)
)
PCTFREE 25
PARTITION BY RANGE (RECORD_VALID_FROM)
SUBPARTITION BY LIST (SYSTEM_ID)
(
  PARTITION P_PRE2006 VALUES LESS THAN (TO_DATE('2006-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  TABLESPACE VORTEX_BUSS_DATA_PRE2006
  COMPRESS FOR ARCHIVE HIGH NO INMEMORY
  (
    SUBPARTITION P_PRE2006_AML VALUES ('AML') TABLESPACE VORTEX_BUSS_DATA_PRE2006
    COMPRESS FOR ARCHIVE HIGH
  , SUBPARTITION P_PRE2006_BMG VALUES ('BMG') TABLESPACE VORTEX_BUSS_DATA_PRE2006
    COMPRESS FOR ARCHIVE HIGH
  , SUBPARTITION P_PRE2006_DEFAULT VALUES (DEFAULT) TABLESPACE VORTEX_BUSS_DATA_PRE2006
    COMPRESS FOR ARCHIVE HIGH
  )
, PARTITION P_202211 VALUES LESS THAN (TO_DATE('2022-12-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  TABLESPACE VORTEX_BUSS_DATA_2022
  COMPRESS FOR ARCHIVE HIGH NO INMEMORY
  (
    SUBPARTITION P_202211_AML VALUES ('AML') TABLESPACE VORTEX_BUSS_DATA_2022
    COMPRESS FOR ARCHIVE HIGH
  , SUBPARTITION P_202211_BMG VALUES ('BMG') TABLESPACE VORTEX_BUSS_DATA_2022
    COMPRESS FOR ARCHIVE HIGH
  , SUBPARTITION P_999999_DEFAULT VALUES (DEFAULT) TABLESPACE VORTEX_BUSS_DATA_9999
    COMPRESS FOR ARCHIVE HIGH
  )
) ENABLE ROW MOVEMENT;


/
