PROMPT Creating Table ENTITY
--ALTER SESSION SET NLS_LENGTH_SEMANTICS = CHAR;
BEGIN

               EXECUTE IMMEDIATE ('DROP TABLE ENTITY');
EXCEPTION

WHEN OTHERS THEN

IF SQLCODE <> -942 THEN

RAISE;

END IF;

END;

/

  CREATE TABLE ENTITY
   (	ENTITY_KEY NUMBER(12,0) NOT NULL ENABLE,
	CODE VARCHAR2(8 CHAR) NOT NULL ENABLE,
	RECORD_VALID_FROM DATE NOT NULL ENABLE,
	RECORD_VALID_UNTIL DATE,
	DESCRIPTION VARCHAR2(200 CHAR) NOT NULL ENABLE,
	IMMEDIATE_LEGAL_PARENT VARCHAR2(8 CHAR),
	IMMEDIATE_ECON_PARENT VARCHAR2(8 CHAR),
	D_LEGAL_BASE_ENTITY_CODE VARCHAR2(15 CHAR),
	BANK_INDICATOR VARCHAR2(1 CHAR),
	ING_TREE VARCHAR2(1 CHAR),
	DESCRIPTION_XML VARCHAR2(800 CHAR),
	CVA_CAP_ELIGIBLE_INCAP VARCHAR2(1 CHAR),
	CVA_CAP_ELIGIBLE_RECAP VARCHAR2(1 CHAR),
	EXCLUDE_FROM_SOLO VARCHAR2(8 CHAR)
   )  ENABLE ROW MOVEMENT COMPRESS;

 PROMPT Creating Index on table ENTITY

  CREATE UNIQUE INDEX IDX_U_ENTITY_KEY ON ENTITY (ENTITY_KEY)
  ;

  CREATE UNIQUE INDEX IDX_UC_ENTITY ON ENTITY (CODE, RECORD_VALID_FROM)
  ;

GRANT SELECT ON ENTITY TO VORTEX_SDP_READ_GRP;

