  CREATE TABLE WORK_AGREEMENT_X_AGREEMENT_ROLE
   (	AGREEMENT_X_AGREEMENT_ROLE_KEY NUMBER NOT NULL ENABLE,
	CODE VARCHAR2(50 CHAR) COLLATE USING_NLS_COMP NOT NULL ENABLE,
	DESCRIPTION VARCHAR2(200 CHAR) COLLATE USING_NLS_COMP NOT NULL ENABLE,
	RECORD_VALID_FROM DATE NOT NULL ENABLE,
	RECORD_VALID_UNTIL DATE,
	LEVEL_NUMBER NUMBER,
	HIGHER_LEVEL_KEY NUMBER,
	HIGHEST_LEVEL_KEY NUMBER
   )  DEFAULT COLLATION USING_NLS_COMP ;

CREATE TABLE WORK_CUST_NATIONAL_CODE_MAP
(	"CUST_NATIONAL_CODE_MAP_KEY" NUMBER(12,0) NOT NULL ENABLE,
"PRIORITY" NUMBER(6,0) NOT NULL ENABLE,
"COUNTRY_CODE" VARCHAR2(10 CHAR) COLLATE "USING_NLS_COMP" DEFAULT NULL,
"SYSTEM_GRID_CODE" VARCHAR2(12 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE,
"RECORD_VALID_FROM" DATE NOT NULL ENABLE,
"RECORD_VALID_UNTIL" DATE DEFAULT NULL
)   ENABLE ROW MOVEMENT ;