CREATE TABLE dmi_customer_new
    ENABLE ROW MOVEMENT
    CLUSTERING BY LINEAR ORDER (RECORD_VALID_UNTIL) YES ON LOAD YES ON DATA MOVEMENT WITHOUT MATERIALIZED ZONEMAP
    PCTFREE 25
    COMPRESS FOR QUERY LOW
AS SELECT * FROM dmi_customer WHERE 1=2;